In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\Irene\Documents\GitHub\python-practice\.venv\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Irene\Documents\GitHub\python-practice\.venv\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Irene\Documents\GitHub\python-practice\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Irene\Documents\GitHub\python-practice\.venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Irene\Documents\GitHub\python-practice\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('ventas_videojuegos.csv')

In [9]:
df.head(1)

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
0,The Elder Scrolls V: Skyrim,X360,Rol,2011.0,Bethesda,7.12,6.35,6.99,2.26,22.72

In [7]:
df.tail(1)

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
203,Call of Duty: Modern Warfare 2,X360,Disparos,2009.0,Activision,5.15,3.59,0.41,1.0,10.15

In [10]:
df.shape

(204, 10)

In [13]:
df.columns

Index(['nombre', 'plataforma', 'genero', 'anio', 'editora', 'ventas_na',
       'ventas_eu', 'ventas_jp', 'ventas_otros', 'ventas_global'],
      dtype='str')

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   nombre         204 non-null    str
 1   plataforma     204 non-null    str
 2   genero         204 non-null    str
 3   anio           197 non-null    float64
 4   editora        199 non-null    str
 5   ventas_na      204 non-null    float64
 6   ventas_eu      204 non-null    float64
 7   ventas_jp      204 non-null    float64
 8   ventas_otros   204 non-null    float64
 9   ventas_global  204 non-null    float64
dtypes: float64(6), str(4)
memory usage: 23.0 KB

In [16]:
df.dtypes

nombre               str
plataforma           str
genero               str
anio             float64
editora              str
ventas_na        float64
ventas_eu        float64
ventas_jp        float64
ventas_otros     float64
ventas_global    float64
dtype: object

In [17]:
df.describe()

,anio,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
count,197.000000,204.000000,204.000000,204.000000,204.000000,204.000000
mean,2011.959391,3.230441,2.640833,1.513676,0.773824,8.158775
std,8.460495,2.761133,2.404268,1.749858,0.747262,7.132819
min,1985.000000,0.210000,0.150000,0.020000,0.030000,0.450000
25%,2007.000000,1.415000,1.157500,0.360000,0.317500,3.545000
50%,2015.000000,2.325000,1.855000,0.905000,0.545000,5.970000
75%,2018.000000,4.097500,3.110000,2.140000,0.957500,9.947500
max,2023.000000,14.590000,12.770000,8.380000,3.710000,31.450000

In [20]:
df.duplicated().sum()

np.int64(4)

In [23]:
df = df.drop_duplicates()

In [24]:
df.shape

(200, 10)

In [26]:
df.isnull().sum()

nombre           0
plataforma       0
genero           0
anio             7
editora          5
ventas_na        0
ventas_eu        0
ventas_jp        0
ventas_otros     0
ventas_global    0
dtype: int64

In [27]:
df['editora'] = df['editora'].fillna('Desconocida')

In [28]:
df.isnull().sum()

nombre           0
plataforma       0
genero           0
anio             7
editora          0
ventas_na        0
ventas_eu        0
ventas_jp        0
ventas_otros     0
ventas_global    0
dtype: int64

In [30]:
df = df.dropna(subset=['anio'])

In [31]:
df.info()

<class 'pandas.DataFrame'>
Index: 193 entries, 0 to 203
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   nombre         193 non-null    str
 1   plataforma     193 non-null    str
 2   genero         193 non-null    str
 3   anio           193 non-null    float64
 4   editora        193 non-null    str
 5   ventas_na      193 non-null    float64
 6   ventas_eu      193 non-null    float64
 7   ventas_jp      193 non-null    float64
 8   ventas_otros   193 non-null    float64
 9   ventas_global  193 non-null    float64
dtypes: float64(6), str(4)
memory usage: 23.3 KB

In [32]:
df['anio']

0      2011.0
1      2018.0
2      2020.0
3      2017.0
4      2021.0
        ...
199    2022.0
200    2017.0
201    2013.0
202    2009.0
203    2009.0
Name: anio, Length: 193, dtype: float64

In [33]:
df['anio'] = df['anio'].astype(int)

In [34]:
df.head()

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
0,The Elder Scrolls V: Skyrim,X360,Rol,2011,Bethesda,7.12,6.35,6.99,2.26,22.72
1,Assassin's Creed Odyssey,PS4,Accion,2018,Ubisoft,3.85,2.99,0.64,0.55,8.03
2,Fall Guys,PS4,Plataformas,2020,Devolver Digital,0.40,0.26,0.15,0.08,0.89
3,Tekken 7,PS4,Lucha,2017,Bandai Namco,1.09,0.90,1.10,0.33,3.42
4,It Takes Two,PS4,Aventura,2021,Electronic Arts,1.11,0.84,0.30,0.20,2.45