In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\Irene\Documents\GitHub\python-practice\.venv\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Irene\Documents\GitHub\python-practice\.venv\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Irene\Documents\GitHub\python-practice\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Irene\Documents\GitHub\python-practice\.venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Irene\Documents\GitHub\python-practice\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('ventas_videojuegos.csv')

In [9]:
df.head(1)

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
0,The Elder Scrolls V: Skyrim,X360,Rol,2011.0,Bethesda,7.12,6.35,6.99,2.26,22.72

In [7]:
df.tail(1)

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
203,Call of Duty: Modern Warfare 2,X360,Disparos,2009.0,Activision,5.15,3.59,0.41,1.0,10.15

In [10]:
df.shape

(204, 10)

In [13]:
df.columns

Index(['nombre', 'plataforma', 'genero', 'anio', 'editora', 'ventas_na',
       'ventas_eu', 'ventas_jp', 'ventas_otros', 'ventas_global'],
      dtype='str')

In [14]:
df.info

<bound method DataFrame.info of                              nombre plataforma       genero    anio  \
0       The Elder Scrolls V: Skyrim       X360          Rol  2011.0
1          Assassin's Creed Odyssey        PS4       Accion  2018.0
2                         Fall Guys        PS4  Plataformas  2020.0
3                          Tekken 7        PS4        Lucha  2017.0
4                      It Takes Two        PS4     Aventura  2021.0
..                              ...        ...          ...     ...
199                      Elden Ring        PS5          Rol  2022.0
200              Gran Turismo Sport        PS4     Carreras  2017.0
201                  The Last of Us        PS3     Aventura  2013.0
202             Assassin's Creed II       X360       Accion  2009.0
203  Call of Duty: Modern Warfare 2       X360     Disparos  2009.0

              editora  ventas_na  ventas_eu  ventas_jp  ventas_otros  \
0            Bethesda       7.12       6.35       6.99          2.26
1             Ubisoft       3.85       2.99       0.64          0.55
2    Devolver Digital       0.40       0.26       0.15          0.08
3        Bandai Namco       1.09       0.90       1.10          0.33
4     Electronic Arts       1.11       0.84       0.30          0.20
..                ...        ...        ...        ...           ...
199      Bandai Namco       2.25       1.82       2.81          0.61
200               NaN       0.33       0.32       0.06          0.05
201              Sony       3.09       2.00       0.87          0.41
202           Ubisoft       3.92       2.72       1.24          0.70
203        Activision       5.15       3.59       0.41          1.00

     ventas_global
0            22.72
1             8.03
2             0.89
3             3.42
4             2.45
..             ...
199           7.49
200           0.76
201           6.37
202           8.58
203          10.15

[204 rows x 10 columns]>